version: '2'
services:
  app-server:
    build: .
    ports:
      - "8080:8080"
    restart: 'no'
    depends_on: 
      - db

  db:
    image: mysql:5.7
    ports:
      - "3206:3306"
    restart: always
    environment:
      MYSQL_DATABASE: terminus
      MYSQL_USER: junaid
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

# Volumes
volumes:
  db-data:
  